language: cpp

matrix:
    include:
      - dist: xenial
      - dist: bionic
      - os: osx
        osx_image: xcode10.3
        env: MODE=Release

addons:
    apt:
        packages:
        - g++
        - libsdl2-dev
        - libpng-dev
        - libjpeg-turbo8-dev
        - libopenal-dev
        - libmad0-dev
        - libglew-dev
        - libgl1-mesa-dev
        - libegl1-mesa-dev
        - libgles2-mesa-dev
        - libpango
        - fonts-linuxlibertine
        - scons
    homebrew:
        packages:
        - gcc
        - libmad
        - libpng
        - jpeg-turbo
        - sdl2
        - pango
        update: true

git:
    quiet: true
    depth: 5

branches:
    except:
        - gh-pages

script:
    - |
        if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
            scons -j2;
            es_path=./finite-galaxy;
        elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
            xcodebuild -configuration $MODE install -quiet
            es_path=/tmp/FiniteGalaxy.dst/Applications/FiniteGalaxy.app/Contents/MacOS/FiniteGalaxy
        fi
    - ./test_parse.sh $es_path

before_cache:
    - brew cleanup

cache:
    directories:
        - $HOME/Library/Caches/Homebrew

notifications:
    email:
        on_success: never
        on_failure: change

